### ISSUE TITLE
cabal-install-1.20.0.3 is built against Cabal-1.20.0.0, but installed library is only Cabal-1.18.1.3

### ISSUE THREAD

**Issue by jystic** [freebroccolo/docker-haskell#19] opened 2015-01-31 03:35 UTC
This seems to cause problems if you try to build a .cabal file that has `cabal-version: >= 1.20.0.0`

Even though `cabal-install-1.20.0.3` is built against `Cabal-1.20.0.0` so you'd think it should work fine, cabal must must require `Cabal-1.20.0.0` to be installed in the package database in order for the build properly.

I would almost say this is a bug in cabal, but it is easily fixable here by adding:

```
RUN cabal install Cabal-1.20.0.0
```

**Comment by ChristopherBiscardi** [comment] 2015-01-31 04:22
I was able to build a cabal file with `cabal-version >= 1.20.0.0` after specifying a `default-language: Haskell2010`

![screenshot 2015-01-30 19 53 21](https://cloud.githubusercontent.com/assets/551247/5986770/81e5d788-a8bd-11e4-9331-cb0aec3edf3c.png)

Do you have a `default-language` in your .cabal?

**Comment by jystic** [comment] 2015-01-31 04:33
Hmm how strange, I definitely have it set.

If you do `docker run <tag> ghc-pkg list | grep Cabal` what do you get?

**Comment by ChristopherBiscardi** [comment] 2015-02-04 15:04
hmm, It would seem that I get cabal-1.18.*. Are there any other requirements to get it to fail? or is it just the `cabal-version`?

**Comment by jystic** [comment] 2015-02-06 00:42
Let me try and put together an example on the weekend, perhaps it's to do with having tests in the project?

**Comment by psftw** [comment] 2015-03-30 15:05
If I look at the PATH in the current haskell image, it doesn't have /root/.cabal/bin first, so you'll wind up running the Debian-packaged cabal executable even after updating it with "cabal install cabal-install' (how meta).  I don't know if this is the cause of the problem you ran in to, but it seems likely.  The fix may just be a PATH change if so.  BTW, cabal fibs a bit :trollface: 

    root@6ccd891fe3e0:/# echo $PATH
    /opt/ghc/7.8.3/bin:/opt/cabal/1.20/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    root@6ccd891fe3e0:/# cabal info Cabal | grep installed
    Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
    update' to download it.
        Versions installed: 1.18.1.3
    root@6ccd891fe3e0:/# cabal --version
    cabal-install version 1.20.0.3
    using version 1.20.0.0 of the Cabal library 

There is no 1.20.0.0 Cabal library in the image anywhere, but that is the minimal version specified by cabal-install.  FWIW, 7.8.4 also ships an older Cabal library (1.18.1.5), whereas 7.10.1 released last Friday ships with the latest 1.22.2.0.

**Comment by ChristopherBiscardi** [comment] 2016-06-03 01:13
closing this since the current version of cabal is 1.22.4 in the 7.10 image

**Closed by ChristopherBiscardi** 2016-06-03 01:13 UTC
