### ISSUE TITLE
cabal install error

### ISSUE THREAD

**Issue by chrissound** [freebroccolo/docker-haskell#48] opened 2016-08-22 21:19 UTC
Apologies for such a short issue but I'm following instructions from https://hub.docker.com/_/haskell/
So using the `Iteratively develop a Haskell application with a Dockerfile utilizing the build cache` approach gives me
`cabal: No sandbox exists at /example/path/here`

Don't we need to create a cabal sandbox?

**Comment by ChristopherBiscardi** [comment] 2016-09-20 14:18
Sorry for the delay, I missed this notification somehow.

The example Dockerfile you are referencing is the same one [located in ~/examples/7.10/snap](https://github.com/freebroccolo/docker-haskell/blob/e0efde5504642864811a7697ab945067bb6a042e/examples/7.10/snap/Dockerfile). I am unable to reproduce the issue. Here are the commands I ran:

```bash
cd examples/7.10/snap
docker build -t adf -f Dockerfile .
```

I'm going to close this one, but feel free to reopen (and please ping me) with more code if this is still an issue for you.

**Closed by ChristopherBiscardi** 2016-09-20 14:18 UTC
